### ISSUE TITLE
Problem inserting data into a posgresSQL database. 

### ISSUE THREAD

**Issue by javier-sanz** [sasakitoa/embulk-input-kafka#7]
Helo Again @sasakitoa 

I was using the plugin with the next `config.yml` to move some data from Kafka to a posgreSQL instance: 

```yml
in:
  type: kafka
  broker_list: my_broker_cluster:9093
  topics:
    - historicPurchases
  key_deserializer: org.apache.kafka.common.serialization.StringDeserializer
  columns:
    - key
    - value
  load_from_beginning: true
  extra_kafka_options:
    auto.offset.reset: earliest
    enable.auto.commit: false
    security.protocol: SSL
    ssl.truststore.location: /Users/jsanz/fluentdData/kafka.client.truststore.jks
    ssl.truststore.password: myPasword
out:
  type: postgresql
  host: localhost
  user: postgres
  password: "myPasword"
  database: test
  table: purchases
  options: {loglevel: 2}
  mode: insert
```
On the log I was seeing some messages being processed but my table `purchases` was empty. Using another `config.yml` with a cvs out I could see mi data. So I finally applied the next patch to the plugin:

```diff
--- a/src/main/java/org/embulk/input/kafka/KafkaInputPlugin.java
+++ b/src/main/java/org/embulk/input/kafka/KafkaInputPlugin.java
@@ -116,6 +116,7 @@ public class KafkaInputPlugin implements InputPlugin {
                 showReadRecords *= 2;
             }
         }
+        builder.finish();
         builder.close();
         logger.info(String.format("Finishing task-%d.Total %d record(s) read in this task", taskIndex, readRecords));
         consumer.close();
```

And that made the difference. Apparently when you close ,`finish()` is not called. And as on my output I was using `insert`mode, that mode only executes the commit at the end of the transaction. Seems the commit is executed on finish builder. That line seems to fixed the problem.
